# Generated by Django 5.1.2 on 2024-11-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='tempetature',
            new_name='temperature',
        ),
    ]
